#!/usr/bin/env python3
"""Build Figure 1 as an editable PowerPoint slide.

Panel A is supplied as a high-resolution workflow image, and panels B-G are
placed from the panel PNG files generated by Figure1.R. The output is intended
as the editable source for final multi-figure assembly and journal export.
"""

from __future__ import annotations

from pathlib import Path

from pptx import Presentation
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN
from pptx.util import Inches, Pt


from path_config import FIG_DIR
OUT_PPTX = FIG_DIR / "Figure1_editable.pptx"


SLIDE_W = 7.5
SLIDE_H = 10.833333333333334


def get_figure1a_panel() -> Path:
    """Return the Figure 1A workflow image supplied by the local user."""
    panel = FIG_DIR / "Figure1A_Workflow_HighRes.png"
    if panel.exists():
        return panel
    raise FileNotFoundError(
        "Provide Figure1A_Workflow_HighRes.png in CFRNA_FIGURE_DIR before "
        "assembling Figure 1."
    )


def add_textbox(slide, text: str, left: float, top: float, width: float, height: float,
                size_pt: float, bold: bool = False) -> None:
    box = slide.shapes.add_textbox(Inches(left), Inches(top), Inches(width), Inches(height))
    tf = box.text_frame
    tf.clear()
    tf.margin_left = 0
    tf.margin_right = 0
    tf.margin_top = 0
    tf.margin_bottom = 0
    p = tf.paragraphs[0]
    p.alignment = PP_ALIGN.LEFT
    run = p.add_run()
    run.text = text
    run.font.name = "Arial"
    run.font.size = Pt(size_pt)
    run.font.bold = bold
    run.font.color.rgb = RGBColor(0, 0, 0)


def add_panel(slide, panel_file: Path, left: float, top: float, width: float, height: float) -> None:
    if not panel_file.exists():
        raise FileNotFoundError(panel_file)
    slide.shapes.add_picture(str(panel_file), Inches(left), Inches(top),
                             width=Inches(width), height=Inches(height))


def main() -> None:
    FIG_DIR.mkdir(parents=True, exist_ok=True)
    panel_a = get_figure1a_panel()

    prs = Presentation()
    prs.slide_width = Inches(SLIDE_W)
    prs.slide_height = Inches(SLIDE_H)
    slide = prs.slides.add_slide(prs.slide_layouts[6])

    add_textbox(slide, "Figure 1", 0.00, 0.00, 1.25, 0.30, 10, bold=False)

    panel_boxes = {
        "A": (0.22, 0.41, 4.78, 2.39, panel_a),
        "B": (5.00, 0.46, 2.28, 2.36, FIG_DIR / "Figure1B_InsertLength.png"),
        "C": (0.21, 3.05, 2.36, 2.36, FIG_DIR / "Figure1C_Biotype_Comparison.png"),
        "D": (2.57, 3.05, 2.36, 2.36, FIG_DIR / "Figure1D_GeneCount.png"),
        "E": (4.93, 3.05, 2.36, 2.36, FIG_DIR / "Figure1E_ShannonEntropy.png"),
        "F": (0.21, 5.75, 2.75, 2.36, FIG_DIR / "Figure1F_PCA.png"),
        "G": (2.97, 5.75, 4.32, 2.36, FIG_DIR / "Figure1G_HexbinPlot.png"),
    }

    for _, (left, top, width, height, file) in panel_boxes.items():
        add_panel(slide, file, left, top, width, height)

    label_positions = {
        "A": (0.21, 0.30),
        "B": (4.98, 0.30),
        "C": (0.21, 2.88),
        "D": (2.48, 2.88),
        "E": (4.83, 2.88),
        "F": (0.21, 5.58),
        "G": (2.95, 5.58),
    }
    for label, (left, top) in label_positions.items():
        add_textbox(slide, label, left, top, 0.20, 0.16, 7, bold=True)

    prs.save(str(OUT_PPTX))
    print(OUT_PPTX)


if __name__ == "__main__":
    main()
