#!/usr/bin/env python3
"""Build combined Figure 1 from the PowerPoint layout.

Panel A is extracted from the submitted PowerPoint. Panels B-G are read from
the revised figure outputs generated by Figure1_revision.R. The layout follows
slide 1 of the submitted PowerPoint.
"""

from __future__ import annotations

from pathlib import Path

from PIL import Image, ImageDraw, ImageFont
from pptx import Presentation


from path_config import BASE_DIR, FIG_DIR

PPTX = BASE_DIR / "FIgure20250812.pptx"

DPI = 600


def px(inch: float) -> int:
    return round(inch * DPI)


def get_font(size: int, bold: bool = False) -> ImageFont.FreeTypeFont:
    candidates = [
        "/System/Library/Fonts/Supplemental/Arial Bold.ttf" if bold else "/System/Library/Fonts/Supplemental/Arial.ttf",
        "/Library/Fonts/Arial Bold.ttf" if bold else "/Library/Fonts/Arial.ttf",
        "/System/Library/Fonts/Helvetica.ttc",
    ]
    for candidate in candidates:
        path = Path(candidate)
        if path.exists():
            return ImageFont.truetype(str(path), size=size)
    return ImageFont.load_default()


def extract_panel_a(out_file: Path) -> None:
    prs = Presentation(str(PPTX))
    slide = prs.slides[0]
    shape = slide.shapes[14]  # PowerPoint shape 15, zero-based index 14
    image = shape.image
    out_file.write_bytes(image.blob)


def paste_fit(canvas: Image.Image, image_file: Path, box: tuple[float, float, float, float]) -> None:
    left, top, width, height = box
    target = (px(width), px(height))
    img = Image.open(image_file).convert("RGBA")
    scale = min(target[0] / img.width, target[1] / img.height)
    resized = (max(1, round(img.width * scale)), max(1, round(img.height * scale)))
    img = img.resize(resized, Image.Resampling.LANCZOS)
    bg = Image.new("RGBA", target, "white")
    x = (target[0] - img.width) // 2
    y = (target[1] - img.height) // 2
    bg.alpha_composite(img, (x, y))
    canvas.alpha_composite(bg, (px(left), px(top)))


def main() -> None:
    FIG_DIR.mkdir(parents=True, exist_ok=True)
    # Use the original PowerPoint-derived workflow panel. A hand-redrawn
    # vector draft was intentionally not used because it did not preserve
    # the submitted layout.
    panel_a = FIG_DIR / "Figure1A_Workflow_from_PowerPoint.png"
    extract_panel_a(panel_a)

    slide_w, slide_h = 7.5, 10.833333333333334
    # Crop to the occupied Figure 1 region while preserving the PowerPoint panel layout.
    crop_h = 8.05
    canvas = Image.new("RGBA", (px(slide_w), px(crop_h)), "white")

    panel_boxes = {
        "A": (0.22, 0.41, 4.78, 2.39, panel_a),
        "B": (5.00, 0.46, 2.28, 2.36, FIG_DIR / "Figure1B_InsertLength.png"),
        "C": (0.21, 2.93, 2.36, 2.36, FIG_DIR / "Figure1C_Biotype_Comparison.png"),
        "D": (2.57, 2.93, 2.36, 2.36, FIG_DIR / "Figure1D_GeneCount.png"),
        "E": (4.93, 2.93, 2.36, 2.36, FIG_DIR / "Figure1E_ShannonEntropy.png"),
        "F": (0.21, 5.44, 2.75, 2.36, FIG_DIR / "Figure1F_PCA.png"),
        "G": (2.97, 5.44, 4.32, 2.36, FIG_DIR / "Figure1G_HexbinPlot.png"),
    }

    for _, (left, top, width, height, file) in panel_boxes.items():
        paste_fit(canvas, file, (left, top, width, height))

    draw = ImageDraw.Draw(canvas)
    title_font = get_font(42, bold=False)
    panel_font = get_font(34, bold=True)
    draw.text((px(0.00), px(0.00)), "Figure 1", fill="black", font=title_font)
    label_positions = {
        "A": (0.21, 0.30),
        "B": (4.98, 0.30),
        "C": (0.21, 2.75),
        "D": (2.48, 2.75),
        "E": (4.83, 2.75),
        "F": (0.21, 5.25),
        "G": (2.95, 5.25),
    }
    for label, (left, top) in label_positions.items():
        draw.text((px(left), px(top)), label, fill="black", font=panel_font)

    png = FIG_DIR / "Figure1_Combined.png"
    tiff = FIG_DIR / "Figure1_Combined.tiff"
    canvas.convert("RGB").save(png, dpi=(DPI, DPI))
    canvas.convert("RGB").save(tiff, dpi=(DPI, DPI), compression="tiff_lzw")
    print(png)
    print(tiff)


if __name__ == "__main__":
    main()
