# Figure7.R
# Final-numbered entry point for Figure 7.
#
# Figure 7 is generated by the shared Figure 6/7 panel generator. Running this
# wrapper regenerates the shared panel set and source-data tables.

rm(list = ls())

cmd_args <- commandArgs(trailingOnly = FALSE)
file_arg <- grep("^--file=", cmd_args, value = TRUE)
this_file <- if (length(file_arg) > 0) sub("^--file=", "", file_arg[1]) else "Figure7.R"
script_dir <- dirname(normalizePath(this_file, mustWork = FALSE))

message("Running shared Figure 6/7 panel generator for final Figure 7.")
source(file.path(script_dir, "Figure6_7_panels.R"), local = new.env(parent = globalenv()))
